baseURL: "https://kunwarutkarsh.tk/"
title: K. Utkarsh
paginate: 50
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: K. Utkarsh
  description: "This is K.Utkarsh's official website."
  keywords: [Blog, Portfolio, Hugo]
  author: K. Utkarsh
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Hello, there!"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: K. Utkarsh
    subtitle: "Frontend Web Developer | FOSS Enthusiast"
    imageUrl: "mk-utkarsh.png"
    imageWidth: 150
    imageHeight: 150
    imageTitle: K. Utkarsh's Logo
    buttons:
      - name: About Me
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/mk-utkarsh"
    - name: dev
      url: "https://dev.to/mk-utkarsh"
    - name: email
      url: "mailto:iusearchbtw2@gmail.com"
    - name: pgp
      url: "https://keys.openpgp.org/search?q=iusearchbtw2%40gmail.com"
    - name: spotify
      url: "https://open.spotify.com/user/31vjectt5tgaa7wpwjjhxkekya3u?si=h2yCkZ6PQ6OYKzjeAFbSg&nd=1"
    
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/mk-utkarsh/kunwarutkarsh.tk/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: post
      name: Posts
      url: /posts/
      weight: 10
    - identifier: archive
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: webrepo
      name: Source Code
      url: https://github.com/mk-utkarsh/kunwarutkarsh.tk.git
      weight: 40
    

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON